/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.ventas;

import dao.DAO_Auto;
import dao.DAO_Cliente;
import dao.DAO_Direccion;
import dao.DAO_Tarjeta;
import dao.DAO_Ventas;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingUtilities;
import modelos.Administrador;
import modelos.Auto;
import modelos.Cliente;
import modelos.Direccion;
import modelos.Tarjeta;
import modelos.Venta;

/**
 *
 * @author rosal
 */
public class DLG_CreateVentas extends javax.swing.JDialog implements Runnable {

    /**
     * Creates new form DLG_CreateVentas
     */
    public DLG_CreateVentas(java.awt.Frame parent, boolean modal, Administrador a) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        hilo.start();
        this.a = a;
    }
    Thread hilo = new Thread(this);
    Administrador a;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JlbVentas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxAuto = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jSpinnerStock = new javax.swing.JSpinner();
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldIdAuto = new javax.swing.JTextField();
        jTextFieldMarca = new javax.swing.JTextField();
        jComboBoxCliente = new javax.swing.JComboBox<>();
        jTextFieldIdCliente = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldIdDireccion = new javax.swing.JTextField();
        jTextFieldCalle = new javax.swing.JTextField();
        jTextFieldNumero = new javax.swing.JTextField();
        jTextFieldCp = new javax.swing.JTextField();
        jTextFieldCiudad = new javax.swing.JTextField();
        jTextFieldColonia = new javax.swing.JTextField();
        jTextFieldIdTarjeta = new javax.swing.JTextField();
        jTextFieldBanco = new javax.swing.JTextField();
        jTextFieldNoTarjeta = new javax.swing.JTextField();
        jComboBoxDireccion = new javax.swing.JComboBox<>();
        jComboBoxTarjeta = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JlbVentas.setFont(new java.awt.Font("Futurist Fixed-width", 1, 36)); // NOI18N
        JlbVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlbVentas.setText("VENTAS");
        JlbVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JlbVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JlbVentas.setInheritsPopupMenu(false);
        getContentPane().add(JlbVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        jLabel2.setFont(new java.awt.Font("Futurist Fixed-width", 0, 10)); // NOI18N
        jLabel2.setText("Selecciona un auto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, 20));

        jComboBoxAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAutoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 271, -1));

        jLabel6.setFont(new java.awt.Font("Futurist Fixed-width", 0, 10)); // NOI18N
        jLabel6.setText("Cantidad");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, -1, 40));
        getContentPane().add(jSpinnerStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, -1, -1));

        jTextFieldModelo.setEditable(false);
        getContentPane().add(jTextFieldModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 209, -1));

        jTextFieldPrecio.setEditable(false);
        getContentPane().add(jTextFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 209, -1));

        jTextFieldIdAuto.setEditable(false);
        getContentPane().add(jTextFieldIdAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 209, -1));

        jTextFieldMarca.setEditable(false);
        getContentPane().add(jTextFieldMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 209, -1));

        jComboBoxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 307, -1));

        jTextFieldIdCliente.setEditable(false);
        getContentPane().add(jTextFieldIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, 54, -1));

        jTextFieldNombre.setEditable(false);
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, 180, -1));

        jTextFieldApellido.setEditable(false);
        getContentPane().add(jTextFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 180, -1));

        jTextFieldIdDireccion.setEditable(false);
        getContentPane().add(jTextFieldIdDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 49, -1));

        jTextFieldCalle.setEditable(false);
        getContentPane().add(jTextFieldCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 191, -1));

        jTextFieldNumero.setEditable(false);
        getContentPane().add(jTextFieldNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 203, -1));

        jTextFieldCp.setEditable(false);
        getContentPane().add(jTextFieldCp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 71, -1));

        jTextFieldCiudad.setEditable(false);
        getContentPane().add(jTextFieldCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 191, -1));

        jTextFieldColonia.setEditable(false);
        getContentPane().add(jTextFieldColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 203, -1));

        jTextFieldIdTarjeta.setEditable(false);
        getContentPane().add(jTextFieldIdTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, 40, -1));

        jTextFieldBanco.setEditable(false);
        getContentPane().add(jTextFieldBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, 245, -1));

        jTextFieldNoTarjeta.setEditable(false);
        getContentPane().add(jTextFieldNoTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 245, -1));

        jComboBoxDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDireccionActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 307, -1));

        jComboBoxTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTarjetaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 307, -1));

        jButton1.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Btn.png"))); // NOI18N
        jButton1.setText("GUARDAR COMPRA");
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 300, 30));

        jButton2.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Btn.png"))); // NOI18N
        jButton2.setText("SALIR");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, -1, -1));

        jLabel23.setFont(new java.awt.Font("Futurist Fixed-width", 0, 12)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("DATOS DEL AUTO");
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 310, 20));

        jLabel24.setFont(new java.awt.Font("Futurist Fixed-width", 0, 10)); // NOI18N
        jLabel24.setText("ID Auto");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 20));

        jLabel25.setFont(new java.awt.Font("Futurist Fixed-width", 0, 10)); // NOI18N
        jLabel25.setText("Marca");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 20));

        jLabel26.setFont(new java.awt.Font("Futurist Fixed-width", 0, 10)); // NOI18N
        jLabel26.setText("Modelo");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 204, -1, 20));

        jLabel27.setFont(new java.awt.Font("Futurist Fixed-width", 0, 10)); // NOI18N
        jLabel27.setText("Precio");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 20));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Futurist Fixed-width", 0, 10)); // NOI18N
        jLabel28.setText("Selecciona una direccion");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        jLabel29.setFont(new java.awt.Font("Futurist Fixed-width", 0, 10)); // NOI18N
        jLabel29.setText("Selecciona un cliente");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        jLabel30.setFont(new java.awt.Font("Futurist Fixed-width", 0, 10)); // NOI18N
        jLabel30.setText("Selecciona una tarjeta");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        jLabel32.setFont(new java.awt.Font("Futurist Fixed-width", 0, 12)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("TARJETA");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 300, -1));

        jLabel33.setFont(new java.awt.Font("Futurist Fixed-width", 0, 12)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("DATOS DEL CLIENTE");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 310, -1));

        jLabel34.setFont(new java.awt.Font("Futurist Fixed-width", 0, 10)); // NOI18N
        jLabel34.setText("Apellido");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, -1, 20));

        jLabel35.setFont(new java.awt.Font("Futurist Fixed-width", 0, 10)); // NOI18N
        jLabel35.setText("Nombre");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, -1, 20));

        jLabel36.setFont(new java.awt.Font("Futurist Fixed-width", 0, 10)); // NOI18N
        jLabel36.setText("ID Cliente");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, -1, 20));

        jLabel37.setFont(new java.awt.Font("Futurist Fixed-width", 0, 10)); // NOI18N
        jLabel37.setText("ID Direccion");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, 20));

        jLabel38.setFont(new java.awt.Font("Futurist Fixed-width", 0, 10)); // NOI18N
        jLabel38.setText("Numero");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, 20));

        jLabel39.setFont(new java.awt.Font("Futurist Fixed-width", 0, 10)); // NOI18N
        jLabel39.setText("Colonia");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, 30));

        jLabel40.setFont(new java.awt.Font("Futurist Fixed-width", 0, 10)); // NOI18N
        jLabel40.setText("Ciudad");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, 30));

        jLabel41.setFont(new java.awt.Font("Futurist Fixed-width", 0, 10)); // NOI18N
        jLabel41.setText("Calle");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 50, 30));

        jLabel42.setFont(new java.awt.Font("Futurist Fixed-width", 0, 10)); // NOI18N
        jLabel42.setText("CP");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 30, 30));

        jLabel43.setFont(new java.awt.Font("Futurist Fixed-width", 0, 10)); // NOI18N
        jLabel43.setText("ID Tarjeta");
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, -1, 20));

        jLabel44.setFont(new java.awt.Font("Futurist Fixed-width", 0, 10)); // NOI18N
        jLabel44.setText("Banco");
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, -1, 20));

        jLabel45.setFont(new java.awt.Font("Futurist Fixed-width", 0, 10)); // NOI18N
        jLabel45.setText("No.Tarjeta");
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, -1, 20));

        jLabel47.setFont(new java.awt.Font("Futurist Fixed-width", 0, 10)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("DATOS DEL CLIENTE");
        jLabel47.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 240, 20));

        jLabel46.setFont(new java.awt.Font("Futurist Fixed-width", 0, 12)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("DIRECCION DEL CLIENTE");
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 300, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BgDimension4.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -230, 1000, 960));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAutoActionPerformed
        // TODO add your handling code here:
        int id_auto = jComboBoxAuto.getItemAt(jComboBoxAuto.getSelectedIndex()).getId();
        String marca = jComboBoxAuto.getItemAt(jComboBoxAuto.getSelectedIndex()).getMarca();
        String modelo = jComboBoxAuto.getItemAt(jComboBoxAuto.getSelectedIndex()).getModelo();
        float precio = jComboBoxAuto.getItemAt(jComboBoxAuto.getSelectedIndex()).getPrecio();
        int stock = jComboBoxAuto.getItemAt(jComboBoxAuto.getSelectedIndex()).getStock();

        jTextFieldIdAuto.setText(String.valueOf(id_auto));
        jTextFieldMarca.setText(marca);
        jTextFieldModelo.setText(modelo);
        jTextFieldPrecio.setText(String.valueOf(precio));

        SpinnerNumberModel spinnerModel = new SpinnerNumberModel(0, 0, stock, 1);
        jSpinnerStock.setModel(spinnerModel);
    }//GEN-LAST:event_jComboBoxAutoActionPerformed

    private void jComboBoxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClienteActionPerformed
        // TODO add your handling code here:
        int id_cliente = jComboBoxCliente.getItemAt(jComboBoxCliente.getSelectedIndex()).getId();
        String nombre = jComboBoxCliente.getItemAt(jComboBoxCliente.getSelectedIndex()).getNombre();
        String apellido = jComboBoxCliente.getItemAt(jComboBoxCliente.getSelectedIndex()).getApellido();

        jTextFieldIdCliente.setText(String.valueOf(id_cliente));
        jTextFieldNombre.setText(nombre);
        jTextFieldApellido.setText(apellido);

        SwingUtilities.invokeLater(() -> {
            jComboBoxDireccion.setModel(new DAO_Direccion().listaDireccion(id_cliente));
        });

        SwingUtilities.invokeLater(() -> {
            jComboBoxTarjeta.setModel(new DAO_Tarjeta().listaTarjeta(id_cliente));
        });
    }//GEN-LAST:event_jComboBoxClienteActionPerformed

    private void jComboBoxDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDireccionActionPerformed
        // TODO add your handling code here:

        int id_direccion = jComboBoxDireccion.getItemAt(jComboBoxDireccion.getSelectedIndex()).getId();
        int numero = jComboBoxDireccion.getItemAt(jComboBoxDireccion.getSelectedIndex()).getNumero();
        int cp = jComboBoxDireccion.getItemAt(jComboBoxDireccion.getSelectedIndex()).getCp();
        String calle = jComboBoxDireccion.getItemAt(jComboBoxDireccion.getSelectedIndex()).getCalle();
        String ciudad = jComboBoxDireccion.getItemAt(jComboBoxDireccion.getSelectedIndex()).getCiudad();
        String colonia = jComboBoxDireccion.getItemAt(jComboBoxDireccion.getSelectedIndex()).getColonia();

        jTextFieldIdDireccion.setText(String.valueOf(id_direccion));
        jTextFieldCalle.setText(calle);
        jTextFieldCiudad.setText(ciudad);
        jTextFieldColonia.setText(colonia);
        jTextFieldCp.setText(String.valueOf(cp));
        jTextFieldNumero.setText(String.valueOf(numero));

    }//GEN-LAST:event_jComboBoxDireccionActionPerformed

    private void jComboBoxTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTarjetaActionPerformed
        // TODO add your handling code here:
        String banco = jComboBoxTarjeta.getItemAt(jComboBoxTarjeta.getSelectedIndex()).getBanco();
        String noTarjeta = jComboBoxTarjeta.getItemAt(jComboBoxTarjeta.getSelectedIndex()).getNoTarjeta();
        int id_tarjeta = jComboBoxTarjeta.getItemAt(jComboBoxTarjeta.getSelectedIndex()).getId();

        jTextFieldBanco.setText(banco);
        jTextFieldNoTarjeta.setText(Tarjeta.verTarjeta(noTarjeta));
        jTextFieldIdTarjeta.setText(String.valueOf(id_tarjeta));
    }//GEN-LAST:event_jComboBoxTarjetaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int id_administrador = a.getId();
        int id_cliente = jComboBoxCliente.getItemAt(jComboBoxCliente.getSelectedIndex()).getId();
        int id_auto = jComboBoxAuto.getItemAt(jComboBoxAuto.getSelectedIndex()).getId();

        float precio = jComboBoxAuto.getItemAt(jComboBoxAuto.getSelectedIndex()).getPrecio();
        int cantidad = (int) jSpinnerStock.getValue();
        float subtotal = precio * cantidad;

        int id_direccion = jComboBoxDireccion.getItemAt(jComboBoxDireccion.getSelectedIndex()).getId();
        int id_tarjeta = jComboBoxTarjeta.getItemAt(jComboBoxTarjeta.getSelectedIndex()).getId();

        DAO_Ventas dao = new DAO_Ventas();
        dao.createVentas(new Venta(id_administrador, id_cliente, id_auto, cantidad, subtotal, id_direccion, id_tarjeta), a);

        limpiacajas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        hilo.interrupt();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlbVentas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<Auto> jComboBoxAuto;
    private javax.swing.JComboBox<Cliente> jComboBoxCliente;
    private javax.swing.JComboBox<Direccion> jComboBoxDireccion;
    private javax.swing.JComboBox<Tarjeta> jComboBoxTarjeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSpinner jSpinnerStock;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldBanco;
    private javax.swing.JTextField jTextFieldCalle;
    private javax.swing.JTextField jTextFieldCiudad;
    private javax.swing.JTextField jTextFieldColonia;
    private javax.swing.JTextField jTextFieldCp;
    private javax.swing.JTextField jTextFieldIdAuto;
    private javax.swing.JTextField jTextFieldIdCliente;
    private javax.swing.JTextField jTextFieldIdDireccion;
    private javax.swing.JTextField jTextFieldIdTarjeta;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldNoTarjeta;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldPrecio;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        jComboBoxAuto.setModel(new DAO_Auto().listaAutos());
        jComboBoxCliente.setModel(new DAO_Cliente().listaClientes());
    }

    private void limpiacajas() {
        jTextFieldIdAuto.setText("");
        jTextFieldMarca.setText("");
        jTextFieldModelo.setText("");
        jTextFieldPrecio.setText("");

        jTextFieldIdCliente.setText("");
        jTextFieldNombre.setText("");
        jTextFieldApellido.setText("");

        jTextFieldIdDireccion.setText("");
        jTextFieldCalle.setText("");
        jTextFieldCiudad.setText("");
        jTextFieldColonia.setText("");
        jTextFieldCp.setText("");
        jTextFieldNumero.setText("");

        jTextFieldIdTarjeta.setText("");
        jTextFieldBanco.setText("");
        jTextFieldNoTarjeta.setText("");

        jSpinnerStock.setValue(0);

        jComboBoxAuto.setSelectedIndex(0);
        jComboBoxCliente.setSelectedIndex(0);

    }
}
